### PR TITLE
utest dependency

### PR DESCRIPTION
**Pull request by kerimdzhanov**
Issued by #3.
Runtime dependency removed.
Development dependency updated.
`make test` successfully passed.

### CODE REVIEW

**Comment by kerimdzhanov** [comment]
Let me know if i've done something wrong.
Please, give me a chance! :)

**Comment by felixge** [comment]
LGTM - thx!

**Comment by felixge** [comment]
Released as 0.0.7 / a44af5b4b913170b85579c374926be405a8a847a

**Comment by kerimdzhanov** [comment]
I was glad to help, thank you!

**Pull request merged**
