### PR TITLE
Print out stdout, even if test passes.

### PR DESCRIPTION
**Pull request by nanek**
I'd like to see any console.log output that is in a test regardless of whether it passes or not. This simplifies debugging tests. For example, if I add a console.log statement to a test, I would expect it to print regardless of the test passing or not, however currently it does not.

### CODE REVIEW

**Comment by felixge** [comment]
The current behavior was intentional / I wanted to only see the output for failing tests. So maybe this could be an environment variable, or other config option?

**Comment by nanek** [comment]
Backstory, i'm starting to work with node-mysql, and there are some tests that fail for me. In attempting to determine the root cause it took me awhile to determine that urun was hiding the stdout on passing tests. In general the output of the tests when passing is blank, so for most tests making this change would have no effect. I'm not sure when you would have a console.log in a test unless you are debugging, but I appreciate there could be use cases i'm not considering.

Either way, i'd rather see it as a config option than not at all. I'll update this soon.

**Comment by nanek** [comment]
@felixge I put this behind the config option `verbose: true`

**Comment by felixge** [comment]
@nanek sweet - thank you so much. Would you like git/npm push access to make a release?

**Comment by nanek** [comment]
That would be great, thanks.

**Pull request merged**
